### ISSUE TITLE
Try to add a loop to reduce code duplication

### ISSUE THREAD

**Issue by Razuuu** [TechPro424/FabricOptimize#4]
https://github.com/TechPro424/FabricOptimize/blob/315b6a574adad60d5c35d4a38b1aebcd5d27f4ef/Installation.ps1#L29

**Comment by TechPro424** [comment]
Fixed in 501f784
Also, I can't remember which mod has the ID `256717` on CF
Could you maybe find which mod on curseforge has the ID `256717`?

**Comment by Razuuu** [comment]
// reopen
![grafik](https://user-images.githubusercontent.com/40471551/226115153-8944dca3-986c-4b4a-a438-47b13b6c45a7.png)

**Comment by TechPro424** [comment]
@Razuuu 
Thanks for finding the mod!
You asked me to reopen, what's the problem?

**Comment by Razuuu** [comment]
I just wanted to show the mod, nothing else
